# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference

version: 2.1
orbs:
  cypress: cypress-io/cypress@2.1.0
executors:
  with-chrome:
    docker:
      - image: 'cypress/browsers:node16.17.1-chrome106-ff105-edge'
workflows:
  build:
    jobs:
      - cypress/run:
          name: Basic tests
          store_artifacts: true
          executor: with-chrome
          browser: chrome
          spec: cypress/auth/*
          filters:
            branches:
              only:  #only | ignore
                - master