# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference


version: 2.1

orbs:
  cypress: cypress-io/cypress@1.29.0
  node: circleci/node@5.0.3

jobs:
  install_cypress:
    executor:  cypress/browsers:node16.17.1-chrome106-ff105-edge  #cypress/browsers-chrome77
    steps:
      - checkout
      - cypress/install

  run_cypress:
    executor:  cypress/browsers:node16.17.1-chrome106-ff105-edge
    circleci_ip_ranges: true
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Show IP address
          command: curl -s https://checkip.amazonaws.com/
      - run: npm run cypress

workflows:
  cypress:
    jobs:
      - install_cypress
      - run_cypress:
          requires:
            - install_cypress